//! Raw FFI bindings to DPDK, generated by bindgen at build time.
//!
//! These bindings are auto-generated from the DPDK headers installed on the
//! build machine. The `build.rs` script uses `pkg-config` to find the headers
//! and `bindgen` to produce this file. Only the subset of DPDK we need is
//! exposed (EAL, mempool, ethdev, mbuf).

// Suppress warnings from bindgen-generated code. These are applied at
// the module level so they cover everything in the included file.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::useless_transmute,
    clippy::unnecessary_cast,
    clippy::too_many_arguments,
    clippy::ptr_offset_with_cast
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/dpdk_bindings.rs"));
}

pub use bindings::*;
